<?php 
/*
Elxis CMS temporary global configuration file
Copyright elxis.org 2006-2010
*/

$tmpConfig = array(
	'offline' => '0',
	'host' => 'localhost',
	'user' => '',
	'password' => '',
	'db' => '',
	'dbtype' => 'mysql',
	'dbprefix' => 'elx_',
	'lang' => 'english',
	'pub_langs' => 'english',
	'alang' => 'english',
	'absolute_path' => '',
	'live_site' => '',
	'sitename' => 'Elxis 2009.2',
	'shownoauth' => '0',
	'useractivation' => '1',
	'uniquemail' => '1',
	'offline_message' => 'This site is down for maintenance.<br />Please check back again soon.',
	'error_message' => 'This site is temporarily unavailable.<br />Please notify the System Administrator',
	'debug' => '0',
	'lifetime' => '3600',
	'MetaDesc' => 'elxis - Open Source CMS',
	'MetaKeys' => 'elxis cms, open source, multilingual, free cms, content managment, rtl compatible, web standards, elxis.org, adodb, xhtml valid',
	'locale' => '',
	'offset' => '0',
	'hideAuthor' => '0',
	'hideCreateDate' => '0',
	'hideModifyDate' => '0',
	'hideRtf' => '0',
	'hidePdf' => '0',
	'hidePrint' => '0',
	'hideEmail' => '0',
	'enable_log_items' => '0',
	'enable_log_searches' => '0',
	'enable_stats' => '0',
	'sef' => '0',
	'vote' => '0',
	'gzip' => '0',
	'multipage_toc' => '1',
	'allowUserRegistration' => '1',
	'link_titles' => '0',
	'error_reporting' => -1,
	'list_limit' => '20',
	'caching' => '0',
	'static_cache' => '0',
	'cachepath' => '',
	'cachetime' => '3600',
	'mailer' => 'mail',
	'mailfrom' => '',
	'fromname' => 'Elxis 2009.2',
	'sendmail' => '/usr/sbin/sendmail',
	'smtpauth' => '0',
	'smtpuser' => '',
	'smtppass' => '',
	'smtphost' => 'localhost',
	'back_button' => '0',
	'item_navigation' => '1',
	'secret' => '',
	'readmore' => '1',
	'hits' => '1',
	'comments' => '1',
	'icons' => '1',
	'favicon' => 'favicon.ico',
	'fileperms' => '',
	'dirperms' => '',
	'helpurl' => '',
	'ftp' => '0',
	'ftp_host' => 'localhost',
	'ftp_user' => '',
	'ftp_pass' => '',
	'ftp_port' => '21',
	'ftp_root' => '',
	'access' => '1',
	'captcha' => '0'
);

?>