
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Насловна', 'index.php?option=com_frontpage', 'components', 1, 0, 10, 0, 1, 0, '1979-12-19 00:00:00', 0, 0, 29, 3, 'menu_image=-1\nmenu_image_only=0\npageclass_sfx=\ntextclass_sfx=\nheader=\npage_title=0\nback_button=0\nleading=1\nintro=4\ncolumns=2\nlink=2\norderby_pri=\norderby_sec=front\npagination=2\npagination_results=0\nimage=1\nsection=0\nsection_link=0\ncategory=0\ncategory_link=0\nitem_title=1\nlink_titles=\nreadmore=\nrating=\nauthor=\ncreatedate=\nmodifydate=\npdf=0\nrtf=0\nprint=0\nemail=0', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Упознајте Elxis', 'index.php?option=com_content&task=section&id=3', 'content_section', 1, 0, 3, 0, 3, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npage_title=1\npageclass_sfx=\nback_button=1\norderby=\nother_cat_section=1\ndescription=1\ndescription_image=1\nother_cat=1\nempty_cat=1\ncat_items=1\ncat_description=1\ndate_format=\ndate=\nauthor=\nhits=\nheadings=1\nnavigation=0\norder_select=0\ndisplay=0\ndisplay_num=50\nfilter=0\nfilter_type=title', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Олакшајте себи', 'index.php?option=com_content&task=category&sectionid=3&id=4', 'content_category', 1, 12, 4, 0, 1, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npage_title=1\npageclass_sfx=\nback_button=1\norderby=\ndate_format=\ndate=\nauthor=\nhits=\nheadings=1\nnavigation=0\norder_select=0\ndisplay=0\ndisplay_num=50\nfilter=0\nfilter_type=title\nother_cat=1\nempty_cat=1\ncat_items=1\ncat_description=1', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Изузетне могућности', 'index.php?option=com_content&task=category&sectionid=3&id=5', 'content_category', 1, 12, 5, 0, 2, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npage_title=1\npageclass_sfx=\nback_button=1\norderby=\ndate_format=\ndate=\nauthor=\nhits=\nheadings=1\nnavigation=0\norder_select=0\ndisplay=0\ndisplay_num=50\nfilter=0\nfilter_type=title\nother_cat=1\nempty_cat=1\ncat_items=1\ncat_description=1', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Сигурност', 'index.php?option=com_content&task=category&sectionid=3&id=6', 'content_category', 1, 12, 6, 0, 3, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npage_title=1\npageclass_sfx=\nback_button=1\norderby=\ndate_format=\ndate=\nauthor=\nhits=\nheadings=1\nnavigation=0\norder_select=0\ndisplay=0\ndisplay_num=50\nfilter=0\nfilter_type=title\nother_cat=1\nempty_cat=1\ncat_items=1\ncat_description=1', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Честа питања', 'index.php?option=com_content&task=blogsection&id=2', 'content_blog_section', 1, 0, 2, 0, 5, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npageclass_sfx=\nback_button=\nheader=\npage_title=1\nleading=0\nintro=10\ncolumns=1\nlink=4\norderby_pri=\norderby_sec=order\npagination=2\npagination_results=1\nimage=1\ndescription=0\ndescription_image=0\ncategory=0\ncategory_link=0\nitem_title=1\nlink_titles=\nreadmore=\nrating=0\nauthor=0\ncreatedate=\nmodifydate=0\nrtf=0\npdf=0\nprint=0\nemail=0\nsectionid=2', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Elxis лиценца', 'index.php?option=com_content&task=view&id=17', 'content_typed', 1, 0, 17, 0, 7, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0', 'srpski',NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Вести', 'index.php?option=com_newsfeeds', 'components', 1, 0, 12, 0, 10, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npageclass_sfx=\nback_button=1\npage_title=1\nheader=\nother_cat_section=1\nother_cat=1\ncat_description=1\ncat_items=1\ndescription=1\ndescription_text=This is a collection of RSS News Feeds, drawn into this site through use of the Newsfeed component\nimage=-1\nimage_align=right\nheadings=1\nname=1\narticles=1\nlink=0\nfeed_image=1\nfeed_descr=1\nitem_descr=1\nword_count=0', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'mainmenu', 'Напредна претрага', 'index.php?option=com_search', 'components', 1, 0, 16, 0, 12, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=\nmenu_image_only=0\npageclass_sfx=\nback_button=\npage_title=1\nheader=', 'srpski', NULL);

INSERT INTO #__menu VALUES (NULL, 'topmenu', 'Насловна', 'index.php?option=com_frontpage', 'components', 1, 0, 10, 0, 1, 0, '1979-12-19 00:00:00', 0, 0, 29, 3, 'menu_image=-1\nmenu_image_only=0\npageclass_sfx=\ntextclass_sfx=\nheader=\npage_title=0\nback_button=0\nleading=1\nintro=4\ncolumns=2\nlink=2\norderby_pri=\norderby_sec=front\npagination=2\npagination_results=0\nimage=1\nsection=0\nsection_link=0\ncategory=0\ncategory_link=0\nitem_title=1\nlink_titles=\nreadmore=\nrating=\nauthor=\ncreatedate=\nmodifydate=\npdf=0\nrtf=0\nprint=0\nemail=0', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'topmenu', 'Линкови', 'index.php?option=com_weblinks', 'components', 1, 0, 4, 0, 3, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npageclass_sfx=\nback_button=\nlastmodified=1\nhits=\nitem_description=1\nother_cat_section=1\nother_cat=1\ndescription=1\ndescription_text=\nimage=-1\nimage_align=right\nweblink_icons=\nsshots=1', 'srpski', NULL);
INSERT INTO #__menu VALUES (NULL, 'topmenu', 'Контакт', 'index.php?option=com_contact&task=view&contact_id=1', 'contact_item_link', 1, 0, 1, 0, 5, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0\npageclass_sfx=\npage_title=1\nheader=', 'srpski', NULL);

INSERT INTO #__menu VALUES (NULL, 'othermenu', 'Администрација', 'administrator/', 'url', 1, 0, 0, 0, 3, 0, '1979-12-19 00:00:00', 0, 0, 29, 0, 'menu_image=-1\nmenu_image_only=0', 'srpski', NULL);
