<?php 
/**
* @ Version: $Id: messages.class.php 1878 2008-01-25 21:26:29Z datahell $
* @ Copyright: Copyright (C) 2006-2008 Elxis.org. All rights reserved.
* @ Package: Elxis
* @ Subpackage: Messages
* @ Author: Elxis Team
* @ E-mail: info@elxis.org
* @ URL: http://www.elxis.org
* @ License: http://www.gnu.org/copyleft/gpl.html GNU/GPL
* Elxis CMS is a Free Software
*/

defined( '_VALID_MOS' ) or die( 'Direct Access to this location is not allowed.' );


class mosMessage extends mosDBTable {
	/** @var int Primary key */
	public $message_id=null;
	/** @var int */
	public $user_id_from=null;
	/** @var int */
	public $user_id_to=null;
	/** @var int */
	public $folder_id=null;
	/** @var datetime */
	public $date_time=null;
	/** @var int */
	public $state=null;
	/** @var int */
	public $priority=null;
	/** @var string */
	public $subject=null;
	/** @var text */
	public $message=null;


	/***************/
	/* CONSTRUCTOR */
	/***************/
	public function __construct( &$db ) {
		$this->mosDBTable( '#__messages', 'message_id', $db );
	}


	/****************/
	/* SEND MESSAGE */
	/****************/
	function send( $from_id=null, $to_id=null, $subject=null, $message=null ) {
		global $database, $mosConfig_sitename, $mosConfig_fromname, $mosConfig_mailfrom, $mosConfig_offset, $_VERSION;

		if (defined('_ELXIS_ADMIN')) { global $adminLanguage; }
		if (is_object( $this )) {
			$from_id = $from_id ? $from_id : $this->user_id_from;
			$to_id = $to_id ? $to_id : $this->user_id_to;
			$subject = $subject ? $subject : $this->subject;
			$message = $message ? $message : $this->message;
		}

		$database->setQuery( "SELECT cfg_name, cfg_value FROM #__messages_cfg WHERE user_id='$to_id'");
		$config = $database->loadObjectList( 'cfg_name' );
		$locked = @$config['lock']->cfg_value;
		$domail = @$config['mail_on_new']->cfg_value;

		if (!$locked) {
			$this->user_id_from = $from_id;
			$this->user_id_to = $to_id;
			$this->subject = $subject;
			$this->message = $message;
			$this->date_time = date('Y-m-d H:i:s', time() + ($mosConfig_offset * 3600));

			if ($this->store()) {
				if ($domail) {
					$database->setQuery( "SELECT email, preflang FROM #__users WHERE id='".$to_id."'", '#__', 1, 0 );
					$rec = $database->loadRow();

					$database->setQuery( "SELECT name, username FROM #__users WHERE id='".$from_id."'", '#__', 1, 0 );
					$sen = $database->loadRow();

					if (!$rec || !$sen) {
						//do nothing
					} else {
						$prlang = new prefLang();
						$prlang->load($rec['preflang']);
						$subject = $prlang->lng->_NEW_MESSAGE;

						$x = $sen['name'].' ('.$sen['username'].')';
						$msg = sprintf($prlang->lng->_NEW_PRMSGF, $x);
						$msg .= "\n".$prlang->lng->_LOG_READMSG;
						$msg .= "\n\n".$mosConfig_sitename;
						$msg .= "\n\n\n";
						$msg .= 'Generated by '.$_VERSION->PRODUCT.' '.$_VERSION->RELEASE.'.'.$_VERSION->DEV_LEVEL.' ('.$_VERSION->CODENAME.")\n";
						$msg .= $_VERSION->COPYRIGHT;

						mosMail($mosConfig_mailfrom, $mosConfig_fromname, $rec['email'], $subject, $msg);
					}
				}
				return true;
			}
		} else {
			if (is_object( $this )) {
				if (defined('_ELXIS_ADMIN')) {
					$this->_error = $adminLanguage->A_CMP_MSS_FAIL;
				} else {
					$this->_error = _MESSAGE_FAILED;
				}
			}
		}
		return false;
	}
}
?>